name: AshtonFellerTechnologies
favicon: null
layout_spectrum: 0
typography_spectrum: 0.58799
title: Tech AF
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf7e6'
    - '#281d16'
    - '#726553'
    - '#a82b00'
    - '#eda26a'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
