name: AshtonFellerTechnologies
favicon: null
layout_spectrum: 0.12621865840628743
typography_spectrum: 0.31586131104268134
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6889369729906321
  lightness: 0.9850139669142663
  saturation: 0.10823643626645207
  rhythmicContrast: 0.9722418659366667
purpose: []
