name: AshtonFellerTechnologies
favicon: null
layout_spectrum: 0.23043
typography_spectrum: 0.58799
title: Tech AF
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffcc00'
    - '#afdde9'
    - '#485b60'
    - '#c79f00'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
